done

diff --git a/0x00-python-hello_world/1-run_line b/0x00-python-hello_world/1-run_line
--- a/0x00-python-hello_world/1-run_line
+++ b/0x00-python-hello_world/1-run_line
@@ -1,2 +1,11 @@
-#!/usr/bin/python3
-python3 -c "$PYCODE"
+#!/bin/bash
+pyfile=$PYFILE
+if [ -z "$pyfile" ]; then
+  echo "Error: PYFILE environment variable is not set."
+    exit 1
+    fi
+    if [ ! -f "$pyfile" ]; then
+      echo "Error: Python file '$pyfile' does not exist."
+        exit 1
+        fi
+ python3 "$pyfile"
